digest: 65c389a0
name: dataset
profile: '{"features_cardinality": 93}'
schema: '{"mlflow_tensorspec": {"features": "[{\"name\": \"0\", \"type\": \"tensor\",
  \"tensor-spec\": {\"dtype\": \"float32\", \"shape\": [-1, 224, 224, 3]}}, {\"name\":
  \"1\", \"type\": \"tensor\", \"tensor-spec\": {\"dtype\": \"int32\", \"shape\":
  [-1, 224, 224, 1]}}]", "targets": null}}'
source: '{"tags": {"mlflow.user": "root", "mlflow.source.name": "fileId=1Q5NU6mj5NaeY8c5XHpClYS0yh8ueMnFn",
  "mlflow.source.type": "NOTEBOOK"}}'
source_type: code
