artifact_uri: file:///content/drive/MyDrive/P8/Experiences/562585704017216840/2e1bbdb72d9041b0ade8703f688decb3/artifacts
end_time: 1770060896625
entry_point_name: ''
experiment_id: '562585704017216840'
lifecycle_stage: active
run_id: 2e1bbdb72d9041b0ade8703f688decb3
run_name: UNet_Light_WithAug
source_name: ''
source_type: 4
source_version: ''
start_time: 1770060864428
status: 4
tags: []
user_id: root
